# Site settings

baseurl = "https://www.jyotsnadhakal.com/"
title = "Jyotsna Dhakal"
languageCode = "en-us"
theme = "frances"

# enable specifying emojis in page content (eg: :wave:)
enableEmoji = true

# turn relative urls into absolute
canonifyURLs = true

# enable all of theme's menu items
sectionPagesMenu = "main"

# disable /posts, /categories, /tags
disableKinds = ["page", "taxonomy", "term"]

###############################################################################

# custom navigation menu items
#[[menu.main]]
#  identifier = "contact"
#  name = "Contact"
#  title = "Email"
#  url = "mailto:hello@jyotsnadhakal.com"

# render raw html
[markup.goldmark.renderer]
unsafe= true

# site params
[params]
  author = "Jyotsna Dhakal"
  # TODO
  #description = "Illustrator and graphic designer"
  email = "hello@jyotsnadhakal.com"
  keywords = "illustration, graphic design, art, illustrator, graphic designer, artist"
