# Site settings

baseurl = "/"

title = "Jyotsna Dhakal"
languageCode = "en-us"
theme = "frances"

# ensure base url is always prefixed to all asset urls
# (needed for serving frances theme js/css properly)
canonifyURLs = true

# enable all of theme's menu items
sectionPagesMenu = "main"

# disable /posts, /categories, /tags
disableKinds = ["page", "taxonomy", "term"]

###############################################################################

# custom navigation menu items
#[[menu.main]]
#  identifier = "contact"
#  name = "Contact"
#  title = "Email"
#  url = "mailto:hello@jyotsnadhakal.com"

# render raw html
[markup.goldmark.renderer]
unsafe= true

[params]
  name = "Jyotsna Dhakal"
  # TODO
  #description = "Illustrator and graphic designer"
  email = "hello@jyotsnadhakal.com"
  author = "Jyotsna Dhakal"
  keywords = "illustration, graphic design, art, illustrator, graphic designer, artist"
