# Site settings

baseurl = "/"

title = "Jyotsna Dhakal"
languageCode = "en-us"
theme = "frances"

# ensure base url is always prefixed to all asset urls
# (needed for serving frances theme js/css properly)
canonifyURLs = true

# enable all of theme's menu items
sectionPagesMenu = "main"

# disable /posts and taxonomies
disableKinds = ["page", "taxonomy", "term"]

###############################################################################

# disable /categories, /tags
[Taxonomies]

# custom navigation menu
# navigation menu items
#[[menu.main]]
#  identifier = "contact"
#  name = "Contact"
#  title = "Contact"
#  url = "/contact/"
#[[menu.main]]
#  identifier = "about"
#  name = "About"
#  title = "About Me"
#  url = "/about/"

# render raw html
[markup.goldmark.renderer]
unsafe= true

[params]
  name = "Jyotsna Dhakal"
  #description = "" # TODO
  email = "hello@jyotsnadhakal.com"
  author = "Jyotsna Dhakal"
